// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package message_service is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	Request
	Response
*/
package message_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Text    string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	Subtext string `protobuf:"bytes,2,opt,name=subtext" json:"subtext,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Request) GetSubtext() string {
	if m != nil {
		return m.Subtext
	}
	return ""
}

type Response struct {
	Text    string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	Subtext string `protobuf:"bytes,2,opt,name=subtext" json:"subtext,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Response) GetSubtext() string {
	if m != nil {
		return m.Subtext
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "message_service.Request")
	proto.RegisterType((*Response)(nil), "message_service.Response")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x8d, 0x2f,
	0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x55, 0x32, 0xe7, 0x62, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d,
	0x2e, 0x11, 0x12, 0xe2, 0x62, 0x29, 0x49, 0xad, 0x28, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x02, 0xb3, 0x85, 0x24, 0xb8, 0xd8, 0x8b, 0x4b, 0x93, 0xc0, 0xc2, 0x4c, 0x60, 0x61, 0x18, 0x57,
	0xc9, 0x82, 0x8b, 0x23, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x95, 0x34, 0x9d, 0x46, 0x7e,
	0x5c, 0x7c, 0xbe, 0x10, 0x57, 0x04, 0x43, 0x1c, 0x21, 0x64, 0xc3, 0xc5, 0x1a, 0x9c, 0x58, 0xe9,
	0x59, 0x22, 0x24, 0xa1, 0x87, 0xe6, 0x3e, 0x3d, 0xa8, 0xe3, 0xa4, 0x24, 0xb1, 0xc8, 0x40, 0x6c,
	0x4f, 0x62, 0x03, 0x7b, 0xcd, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x63, 0x98, 0xe2, 0x43, 0xe7,
	0x00, 0x00, 0x00,
}
